name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Installs website-carbon-cli
      - run: npm i website-carbon-cli
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: |
            const {runCarbonTest } = require('website-carbon-cli/website-carbon.js')
            // https://davidwells.io/snippets/regex-match-markdown-links
            console.log(github)
            const getLinksFromMarkdown = mdContents => {
            const regexMdLinks = /\[([^\[]+)\](\(.*\))/gm
            const matches = mdContents.match(regexMdLinks)
            const singleMatch = /\[([^\[]+)\]\((.*)\)/
            const links = matches.map((link)=>{
            const text = singleMatch.exec(link) 
              return { text: text[1], url: text[2] }
            })
            return links
            }
            const links = getLinksFromMarkdown(context.payload.pull_request.body);
            links.foreach(link => {
            const runTest = link.text.substring(0,7).toLowerCase === 'testbox'
            if(runTest){
            runCarbonTest(url)
            .then(json => {
            console.log(json)
            })
            .catch(e => {
            console.log(`🚩 ERROR: `, e)
            })
            }
            })//endforeach
            
            